version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: spark-postgres-db
    environment:
      - "POSTGRES_USER=docker"
      - "POSTGRES_PASSWORD=docker"
    ports:
      - "5432:5432"
    volumes:
      - "./sql:/docker-entrypoint-initdb.d"